%STARTUP

%% add MATPOWER paths
addpath( ...
    'D:\MATLAB\matpower\lib', ...
    'D:\MATLAB\matpower\lib\t', ...
    'D:\MATLAB\matpower\data', ...
    'D:\MATLAB\matpower\most\lib', ...
    'D:\MATLAB\matpower\most\lib\t', ...
    'D:\MATLAB\matpower\mp-opt-model\lib', ...
    'D:\MATLAB\matpower\mp-opt-model\lib\t', ...
    'D:\MATLAB\matpower\mips\lib', ...
    'D:\MATLAB\matpower\mips\lib\t', ...
    'D:\MATLAB\matpower\mptest\lib', ...
    'D:\MATLAB\matpower\mptest\lib\t', ...
    '-end' );
